<a href="https://colab.research.google.com/github/kelvin-kahuho/Machine-learning-crash-course/blob/main/Intro_to_Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**CREATE**

In [2]:
import numpy as np

a = np.array([1,2,3,4,5,6])
zeroes = np.zeros((4,4))
ones = np.ones((2,3))
sevens = np.full((2,2), 7)
range = np.arange(1,100,2).reshape(5,10)



In [3]:
print(a)
print(zeroes)
print(ones)
print(sevens)
print(range)

[1 2 3 4 5 6]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7]
 [7 7]]
[[ 1  3  5  7  9 11 13 15 17 19]
 [21 23 25 27 29 31 33 35 37 39]
 [41 43 45 47 49 51 53 55 57 59]
 [61 63 65 67 69 71 73 75 77 79]
 [81 83 85 87 89 91 93 95 97 99]]


**READ**

In [4]:
print(a.dtype)
print(a.size)
print(a.shape)

int64
6
(6,)


In [8]:
#Slicing

data = np.random.rand(30).reshape(6,5)
index_zero = data[0]
reverse = data[-1]
single_value = data[0][0]


In [9]:
print(data)
print("...")
print(index_zero)
print("...")
print(reverse)
print("...")
print(single_value)

[[0.24069093 0.02227507 0.45599557 0.72177484 0.58566985]
 [0.37012572 0.13386553 0.1759588  0.95083232 0.27283913]
 [0.72595946 0.53537301 0.73964621 0.04589453 0.97775656]
 [0.04119857 0.12818324 0.49423787 0.05325589 0.46033913]
 [0.29553262 0.64110383 0.02888152 0.13070295 0.61267285]
 [0.19031275 0.77934011 0.16622724 0.30945186 0.16712123]]
...
[0.24069093 0.02227507 0.45599557 0.72177484 0.58566985]
...
[0.19031275 0.77934011 0.16622724 0.30945186 0.16712123]
...
0.24069093000555797


**UPDATE**

In [13]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

add = np.add(a, b)
sub = np.subtract(a, b)
div = np.divide(a, b)
multi = np.multiply(a, b)
dot = np.dot(a, b)



In [14]:
print(add)
print("...")
print(sub)
print("...")
print(div)
print("...")
print(multi)
print("...")
print(dot)

[5 7 9]
...
[-3 -3 -3]
...
[0.25 0.4  0.5 ]
...
[ 4 10 18]
...
32


In [15]:
#Statistical Functions

print(np.sqrt(25))
print("...")
print(np.abs(-2))
print("...")
print(np.power(2, 7))
print("...")
print(np.log(25))
print("...")
print(np.exp([2,3]))
print("...")
print(np.min(data))
print(np.max(data))

5.0
...
2
...
128
...
3.2188758248682006
...
[ 7.3890561  20.08553692]
...
0.02227507246690319
0.9777565636621651


In [21]:
#Adding Items to an numpy array
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr = np.append(arr, [13,14,15])
print(arr)
arr = np.insert(arr, 1, 5)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 1  5  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


**DELETE**

In [22]:
arr = np.delete(arr, 5)
print(arr)

[ 1  5  2  3  4  6  7  8  9 10 11 12 13 14 15]
